root: true

plugins:
  - jest

env:
  node: true
  jest: true
  es2021: true

parserOptions:
  ecmaVersion: 2021

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
